//! The `memories` module — long-term facts that outlive the context window.
//!
//! Phase 3 of PLAN.md: when a campaign grows beyond what fits in the provider
//! context, old turns are summarized into memories that are re-injected into
//! the context. Memories are GM-curated (they can be created/edited manually)
//! and best-effort generated by the default provider.

pub mod domain;
pub mod service;
pub mod storage;

#[cfg(feature = "tauri")]
pub mod commands;

pub use domain::{Memory, NewMemory};
pub use service::MemoryService;
