//! The `memories` module — long-term facts that outlive the context window.
//!
//! Phase 3 of PLAN.md: when a campaign grows beyond what fits in the provider
//! context, old turns are summarized into memories that are re-injected into
//! the context. Memories are GM-curated (they can be created/edited manually)
//! and best-effort generated by the default provider.

// Sub-modules compile unconditionally: domain/service/storage carry no Tauri
// dependency, so they stay testable headless (§5.11).
pub mod domain;
pub mod service;
pub mod storage;

// Commands are feature-gated behind `tauri` so the module compiles and tests
// headless without dragging in the webview (and its crate graph, §5.11).
#[cfg(feature = "tauri")]
pub mod commands;

// Re-export the public surface so consumers import the module name rather than
// reaching into sub-modules; the internals stay private (§5.6).
pub use domain::{Memory, NewMemory};
pub use service::MemoryService;
