[package]
name = "roleplayer-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
rusqlite.workspace = true
rusqlite_migration.workspace = true
async-trait.workspace = true
tracing.workspace = true
chrono.workspace = true
