//! Campaign orchestration: the service layer for the `campaigns` module.

use std::sync::Arc;

use roleplayer_core::errors::Result;
use roleplayer_core::storage::Storage;
use roleplayer_core::{new_id, now_rfc3339};

use crate::domain::{Campaign, NewCampaign, UpdateCampaign};
use crate::storage as repo;

/// Orchestrates campaign lifecycle: validates, persists, and returns entities.
///
/// Generic over `S: Storage` so the same service works against the file DB and
/// the in-memory test DB (§5.11 of AGENTS.md). Thin by design (§5.2): no
/// business decisions live here beyond applying the domain rules.
pub struct CampaignService<S: Storage> {
    // Shared seam to the single-writer DB connection; `Arc` lets the service
    // be cloned across async tasks without cloning the underlying connection.
    storage: Arc<S>,
}

impl<S: Storage> CampaignService<S> {
    /// Create a service over the shared storage seam.
    pub fn new(storage: Arc<S>) -> CampaignService<S> {
        // Just wrap the caller-provided storage; the composition root decides
        // which backend (file DB vs. in-memory test DB) to hand in.
        CampaignService { storage }
    }

    /// Create a campaign after validating its input.
    pub fn create(&self, input: NewCampaign) -> Result<Campaign> {
        // Reject malformed input (blank name, oversized fields) up front,
        // before any DB write so a bad create leaves no partial state.
        input.validate()?;
        // One clock read, reused for both timestamps so a fresh row reads
        // created == updated instead of two near-identical instants.
        let now = now_rfc3339();
        let campaign = Campaign {
            // Random UUID v4 generated by the backend; clients never supply
            // ids, which keeps ids trustworthy (§5.4).
            id: new_id(),
            // Trim surrounding whitespace so "  Tavern  " stores cleanly and
            // sorts/looks consistent in the UI list.
            name: input.name.trim().to_string(),
            description: input.description.trim().to_string(),
            // May be None; the turn flow later falls back to the built-in
            // ruleset when no explicit one is bound here.
            ruleset_id: input.ruleset_id,
            // New campaigns carry an empty settings document; the UI adds keys
            // later. A JSON object (not a typed struct) keeps this
            // forward-compatible (§5.4: "any kind of data" starts as JSON).
            settings: serde_json::Value::Object(Default::default()),
            created_at: now.clone(),
            updated_at: now,
        };
        // INSERT the row; a duplicate id would surface here as a typed error.
        repo::insert(self.storage.as_ref(), &campaign)?;
        // Log with the id as a correlation key (§5.13), never the payload.
        tracing::info!(campaign_id = %campaign.id, "campaign created");
        Ok(campaign)
    }

    /// All campaigns, newest first.
    pub fn list(&self) -> Result<Vec<Campaign>> {
        // Pure delegation: ordering by recency lives in the SQL query, not in
        // this service, so one repo handles all list callers consistently.
        repo::list(self.storage.as_ref())
    }

    /// One campaign by id.
    pub fn get(&self, campaign_id: &str) -> Result<Option<Campaign>> {
        // `None` means "not found", which is a normal outcome, not an error —
        // the caller decides how to present a missing campaign to the user.
        repo::get(self.storage.as_ref(), campaign_id)
    }

    /// Update a campaign's editable fields; `None` when the id is unknown.
    pub fn update(
        &self,
        campaign_id: &str,
        input: UpdateCampaign,
    ) -> Result<Option<Campaign>> {
        // Validate the incoming fields before reading the current row, so an
        // invalid update fails without even hitting the DB.
        input.validate()?;
        // Load the existing row first so immutable fields can be carried over
        // verbatim; a missing campaign short-circuits to None instead of
        // pretending an insert or crashing on a null deref.
        let existing = match repo::get(self.storage.as_ref(), campaign_id)? {
            Some(campaign) => campaign,
            None => return Ok(None),
        };
        let updated = Campaign {
            // Preserve the identity and non-editable fields from the stored
            // row; only the user-facing fields below are replaced.
            id: existing.id.clone(),
            // Trimmed like create, so updates follow the same normalization
            // rules as creation.
            name: input.name.trim().to_string(),
            description: input.description.trim().to_string(),
            ruleset_id: input.ruleset_id,
            // Settings aren't editable yet, so carry the stored value over
            // untouched; only name/description/ruleset change on update.
            settings: existing.settings,
            // created_at records birth and never moves on an update.
            created_at: existing.created_at,
            // Touch updated_at so list ordering and UI "edited" badges reflect
            // the modification.
            updated_at: now_rfc3339(),
        };
        // The repo stamps the fresh updated_at in the same write as the row.
        repo::update(self.storage.as_ref(), &updated, &updated.updated_at)?;
        tracing::info!(campaign_id = %campaign_id, "campaign updated");
        Ok(Some(updated))
    }

    /// Delete a campaign (cascades to its children). `true` if it existed.
    pub fn delete(&self, campaign_id: &str) -> Result<bool> {
        // The repo owns the child cascade; the service only reports whether
        // the target row existed so the UI can show the right confirmation.
        let deleted = repo::delete(self.storage.as_ref(), campaign_id)?;
        tracing::info!(campaign_id = %campaign_id, deleted, "campaign delete requested");
        Ok(deleted)
    }
}
